apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test989
  name: test989
  labels:
    app: test989
spec:
  selector:
    matchLabels:
      app: test989
  template:
    metadata:
      labels:
        app: test989
        name: test989
    spec:
      containers:
        - name: test989
          image: chandrababu1609/bheem/test989
          imagePullPolicy: Always
        
          env:
            - name: SERVICE_NAME
              value: "go-app"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "localhost:4317"
            - name: INSECURE_MODE
              value: "true"
        
          ports:
        
        
          - containerPort: 9898
            name: http
        
        
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
        