apiVersion: v1
kind: Service
metadata:
  namespace: test989
  labels:
    app: test989
  name: test989
spec:
  ports:
  
    - protocol: TCP
      port: 9898
      targetPort: 9898
   
   
  selector:
    app: test989
  type: ClusterIP
